Add register command reference
mdbootstrap/mdb-docs-and-content pull request #45
Opened 2020-08-20 14:26 UTC by kpietron

2020-08-24 10:56 UTC, catchmareck requested changes
Two little changes needed.

2020-08-24 10:56 UTC, catchmareck commented on en/_mdb5/standard/web/docs/cli/reference/o.html
> +      <mdbsnippet>
Please add `<!-- prettier-ignore -->` comment before `<mdbsnippet>` tag because Prettier will mess up the indentation here.

2020-08-24 10:56 UTC, catchmareck commented on en/_mdb5/standard/web/docs/cli/reference/o.html
> +      Create your MDB account. It will ask you to provide the username, email and password.
I think we should also point out that the user will be automatically logged in so there's no need to run `mdb login` additionally.

2020-08-24 14:09 UTC, smolenski-mikolaj commented
@cla-bot check

2020-09-03 11:31 UTC, catchmareck approved these changes
LGTM

2020-09-03 11:32 UTC, catchmareck commented
@smolenski-mikolaj I'll merge this into master once we merge the register feature itself in the CLI tool. Until then, this PR needs to wait so please don't merge it yet.

2020-10-09 10:13 UTC, merged