Explicitly mention HammerJs dependency on carousel for mobile devices.
mdbootstrap/mdb-docs-and-content pull request #8
Opened 2019-09-04 00:00 UTC by Razkaroth

This dependency should be made explicit in order to avoid not being able to scroll over carousels. As this is something that new users can easily miss.

2019-09-04 07:12 UTC, idzark commented
Thank you for your contribution. That's good idea, please add this section to the scrollspy as well (o-ss.html file).

2019-09-04 18:27 UTC, Razkaroth commented
Ok, done.

2019-09-05 05:55 UTC, idzark requested changes
Please update the scrollspy link title. It should be 'Mobile devices' instead of 'Full page video carousel'.

2019-09-05 06:01 UTC, Razkaroth commented
My bad. It's been corrected.

2019-09-05 06:02 UTC, idzark approved these changes

2019-09-05 06:03 UTC, merged